appversion: app/v1
kind: Deployment
metadata:
  name: jppapp-deployment
  labels:
    app: jppapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jppapp
  template:
    metadata:
      labels:
        app: jppapp
    spec:
      containers:
      - name: jppapp-container
        image: jppapp:latest
        ports:
        - containerPort: 8080
 